name: teams
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  dots_indicator: ^3.0.0
  formz: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8

flutter:
  assets:
    - assets/

  uses-material-design: true
